### PR TITLE
Updated Translation for Simplified Chinese

### PR DESCRIPTION
**Pull request by oracle5th**
Added translations for a few new terms. Removed unnecessary comments.

### CODE REVIEW

**Comment by zyv** [comment]
@oracle5th thank you for your help!

The `python-format` comments are automatically inserted by our translation system to show translators, that the string contains replacement elements, so it is not necessary to remove them, as they will be inserted back again automatically.

On the other hand, when you translate strings, `fuzzy` comments should be removed, because these are comments by our translation system which say that it is not sure that the translation is still good after minor changes to the source text, or after the text has been moved to a different place on the web page.

My guess is that you downloaded the file, and used a simple text editor to translate. There is a nice free program called [Poedit](https://poedit.net) as explained in the README, which can help you and it understands the comments discussed above.

**Comment by zyv** [comment]
@oracle5th, @masterleague, I suggest the following: I merge this PR as is, and then fix the header myself. :+1: ?

**Comment by oracle5th** [comment]
@zyv 
Thank you for the feedback!

I only manually removed a few comments saying "I can't find the English text on the website." which I assume is left by previous translators. The other changes were automatically made by the Poeditor itself. I used the web-version Poeditor to add a few new translations. I think when the editor parsed the old django.po file, some of the contents that are no longer in the template file django.pot (like those two very long texts at the end) were discarded, so they are not in the exported new django.po file anymore. The header was also changed in the process. I don't really know the syntax of Poeditor, so please go ahead to fix it if needed.

The fuzzy term I changed is "All maps". The term was marked as fuzzy, but no translation was given. However, there was another similar term, "All Maps". I untoggled the fuzzy mark and added the same translation from term "All Maps".

**Comment by zyv** [comment]
@oracle5th, FYI, I've just deployed the new translation to the website. Hope it works!

> The other changes were automatically made by the Poeditor itself. I used the web-version Poeditor to add a few new translations.

Sorry, I'm very confused now, how did you manage to do that?! I thought we have deleted our Poeditor.com account long ago, or did you use your own account? We are now recommending our contributors to use Poedit (without "or"! see link above), which is a free stand-alone program and works really well...

**Comment by oracle5th** [comment]
I used my own account. I imported the terms from the template django.pot and translations from the old .po file, added new translations and then exported a new .po file.
hmm.. I thought Poedit was just a local version of Poeditor. I hope I didn't mess up anything.
I just checked the website. It seems to be working well.

**Comment by zyv** [comment]
Ah, OK, thanks for the explanation. No, Poedit is a free program which is completely unrelated to Poeditor website... maybe you can try it next time ;-)

Good to know that the translation looks fine now! :-)

**Pull request merged**
