### PR TITLE
Small Polish update 11032017

### PR DESCRIPTION
**Pull request by asperaastra**

### CODE REVIEW

**Comment by zyv** [comment]
Thank you, deployed as  eb4deaf . You've almost made it ;-) the problem was you put `django.po` in the wrong (root) directory instead of `locale/pl/LC_MESSAGES`.

**Comment by asperaastra** [comment]
thanks :)

2017-04-16 22:19 GMT+01:00 Yury V. Zaytsev <notifications@github.com>:

**Comment by asperaastra** [comment]
Hi Yury,

I get below message when I try to upload to locale/pl/LC_MESSAGES.  I have
attached the file with the latest translation (counters, favourites) as
without a decent instruction I'm not sure how to do this directly on website

[image: Obraz w treści 1]

2017-04-16 22:19 GMT+01:00 Yury V. Zaytsev <notifications@github.com>:

**Comment by zyv** [comment]
Hi,

Sadly, I can't see what's behind "[image: Obraz w treści 1]". The easiest I think would be just to open the file in the online editor and copy & paste the new contents. Otherwise, I'm flying for a vacation in a few hours, so I'm afraid you'll have to try a bit more yourself :) or else, feel free to send the latest edited file you've got from this repository by email...

Good luck!

**Comment by asperaastra** [comment]
Hi, I have attached it the latest file to my previous email. Thanks

2017-04-17 12:35 GMT+01:00 Yury V. Zaytsev <notifications@github.com>:

**Comment by zyv** [comment]
But you sent the email to GitHub and it removes the attachments!

**Pull request closed without merging**
