### PR TITLE
Add initial version of danish translation

### PR DESCRIPTION
**Pull request by lukaspj**
I did this rather quickly, it should provide a good basis for further improvements.

There are a few inconsistencies and missing translations, I recommend a second revision.

### CODE REVIEW

**Comment by zyv** [comment]
Hey Lukas, thank you for your contribution! We have deployed your translation to our website. Please feel free to check it out and file further pull requests if something has to be adjusted. Also, please let us know how you would like to be credited on our website: https://masterleague.net/credits/ .

**Comment by lukaspj** [comment]
My name (Lukas Joergensen) with a link to my LinkedIn would be grand: https://www.linkedin.com/in/lukaspj/

**Comment by zyv** [comment]
@masterleague could you please take care of this? Many thanks! :-)

**Comment by masterleague** [comment]
Done!

**Pull request merged**
